// Diccionario bilingüe ES/EN para los strings que el .mq5/.mq4 emite a
// MetaTrader. Lo usan tanto mqlGenerator (MQL5) como mql4Generator. El
// usuario abre MetaTrader y ve cada Print/comment/property en su idioma.
//
// Mantenerlo aquí (no inline en los generators) para que las dos versiones
// MQL4/MQL5 nunca queden desincronizadas y para que añadir un idioma futuro
// sea editar UN archivo.

export type Lang = 'es' | 'en';

export const MQL_COPY: Record<Lang, {
  // Header y descriptions del .mq5/.mq4
  headerGenerated: string;     // "Generado por YudBot" / "Generated by YudBot"
  headerEndOfFile: string;     // "END OF FILE — Generado por YudBot"
  propStrategy: string;        // "Estrategia" / "Strategy"
  propPair: string;            // "Par" / "Pair"
  propLeverage: string;        // "Apalancamiento" / "Leverage"

  // Grupos de inputs (los que ve el usuario en el dialog de propiedades del EA)
  groupGeneral: string;
  groupLot: string;
  groupRisk: string;
  groupTime: string;
  groupNews: string;

  // OnInit / OnDeinit prints
  initSymbolError: string;     // "Error: No se puede acceder al símbolo"
  initSuccess: string;         // "Bot inicializado correctamente"
  initBalance: string;         // "Balance inicial:"
  initLeverage: string;        // "Apalancamiento: 1:"
  deinitStopped: string;       // "Bot detenido. Razón:" (solo MQL4)

  // MQL4: validación de símbolo
  chartMismatchPre: string;    // "Error: el bot está configurado para"
  chartMismatchMid: string;    // "pero el chart es"
  chartMismatchTail: string;   // "Adjúntalo a un chart de"

  // OnTick: pérdida diaria
  dailyLossHit: string;        // "⚠️ Pérdida diaria máxima alcanzada"
  dailyLossPaused: string;     // "Bot pausado"

  // OnTick: motivos de skip
  skipDailyLoss: string;       // "[skip] pérdida diaria máxima alcanzada"
  skipHours: string;           // "[skip] fuera de horario ("
  skipBrokerTime: string;      // " hora del broker)"
  skipNews: string;            // "[skip] noticia de alto impacto cercana"
  skipPosition: string;        // "[skip] ya hay una posición abierta de este bot"

  // Comentarios MQL inline (los emite el generator al .mq5/.mq4)
  commentStrategy: string;     // "Estrategia"
  commentIndicators: string;   // "indicadores"
  commentNone: string;         // "(ninguno)"
  commentLogic: string;        // "Lógica: (al menos un trigger fire) AND (todos los filtros confirman)"

  // Trade execution prints (MQL5 con CTrade)
  buyRejected: string;         // "BUY rechazada:"
  buySent: string;             // "BUY enviada:"
  sellRejected: string;        // "SELL rechazada:"
  sellSent: string;            // "SELL enviada:"

  // Trade execution prints (MQL4 con OrderSend)
  buyOpenError: string;        // "Error al abrir BUY:"
  buyOpened: string;           // "BUY abierta · Ticket:"
  sellOpenError: string;       // "Error al abrir SELL:"
  sellOpened: string;          // "SELL abierta · Ticket:"
  lot: string;                 // "Lote:" / "Lot:"

  // Indicator handle creation error: "Error creando ${name}"
  indicatorErrorPrefix: string;
}> = {
  es: {
    headerGenerated: 'Generado por YudBot',
    headerEndOfFile: 'END OF FILE — Generado por YudBot',
    propStrategy: 'Estrategia',
    propPair: 'Par',
    propLeverage: 'Apalancamiento',

    groupGeneral: '═══ CONFIGURACIÓN GENERAL ═══',
    groupLot:     '═══ TAMAÑO DE LOTE ═══',
    groupRisk:    '═══ GESTIÓN DE RIESGO ═══',
    groupTime:    '═══ HORARIO DE OPERACIÓN ═══',
    groupNews:    '═══ FILTRO DE NOTICIAS ═══',

    initSymbolError: 'Error: No se puede acceder al símbolo',
    initSuccess:     'Bot inicializado correctamente',
    initBalance:     'Balance inicial:',
    initLeverage:    'Apalancamiento: 1:',
    deinitStopped:   'Bot detenido. Razón:',

    chartMismatchPre:  'Error: el bot está configurado para',
    chartMismatchMid:  'pero el chart es',
    chartMismatchTail: 'Adjúntalo a un chart de',

    dailyLossHit:    '⚠️ Pérdida diaria máxima alcanzada',
    dailyLossPaused: 'Bot pausado',

    skipDailyLoss:  '[skip] pérdida diaria máxima alcanzada',
    skipHours:      '[skip] fuera de horario (',
    skipBrokerTime: ' hora del broker)',
    skipNews:       '[skip] noticia de alto impacto cercana',
    skipPosition:   '[skip] ya hay una posición abierta de este bot',

    commentStrategy:   'Estrategia',
    commentIndicators: 'indicadores',
    commentNone:       '(ninguno)',
    commentLogic:      'Lógica: (al menos un trigger fire) AND (todos los filtros confirman)',

    buyRejected:  'BUY rechazada:',
    buySent:      'BUY enviada:',
    sellRejected: 'SELL rechazada:',
    sellSent:     'SELL enviada:',

    buyOpenError:  'Error al abrir BUY:',
    buyOpened:     'BUY abierta · Ticket:',
    sellOpenError: 'Error al abrir SELL:',
    sellOpened:    'SELL abierta · Ticket:',
    lot:           'Lote:',

    indicatorErrorPrefix: 'Error creando',
  },
  en: {
    headerGenerated: 'Generated by YudBot',
    headerEndOfFile: 'END OF FILE — Generated by YudBot',
    propStrategy: 'Strategy',
    propPair: 'Pair',
    propLeverage: 'Leverage',

    groupGeneral: '═══ GENERAL SETTINGS ═══',
    groupLot:     '═══ LOT SIZE ═══',
    groupRisk:    '═══ RISK MANAGEMENT ═══',
    groupTime:    '═══ TRADING HOURS ═══',
    groupNews:    '═══ NEWS FILTER ═══',

    initSymbolError: 'Error: cannot access symbol',
    initSuccess:     'Bot initialized successfully',
    initBalance:     'Initial balance:',
    initLeverage:    'Leverage: 1:',
    deinitStopped:   'Bot stopped. Reason:',

    chartMismatchPre:  'Error: bot is configured for',
    chartMismatchMid:  'but the chart is',
    chartMismatchTail: 'Attach it to a chart of',

    dailyLossHit:    '⚠️ Max daily loss reached',
    dailyLossPaused: 'Bot paused',

    skipDailyLoss:  '[skip] max daily loss reached',
    skipHours:      '[skip] outside trading hours (',
    skipBrokerTime: ' broker time)',
    skipNews:       '[skip] high-impact news nearby',
    skipPosition:   '[skip] this bot already has an open position',

    commentStrategy:   'Strategy',
    commentIndicators: 'indicators',
    commentNone:       '(none)',
    commentLogic:      'Logic: (at least one trigger fires) AND (all filters confirm)',

    buyRejected:  'BUY rejected:',
    buySent:      'BUY sent:',
    sellRejected: 'SELL rejected:',
    sellSent:     'SELL sent:',

    buyOpenError:  'Error opening BUY:',
    buyOpened:     'BUY opened · Ticket:',
    sellOpenError: 'Error opening SELL:',
    sellOpened:    'SELL opened · Ticket:',
    lot:           'Lot:',

    indicatorErrorPrefix: 'Error creating',
  },
};

// Bilingüe para el `strategyDescriptions` map del header. Algunas estrategias
// ya tenían texto en inglés en el código original, pero las normalizamos
// todas aquí para tener un único source of truth.
export const STRATEGY_DESC: Record<Lang, Record<string, string>> = {
  es: {
    scalping:  'Scalping rápido (1m-5m timeframe)',
    swing:     'Swing trading (4h-1d timeframe)',
    grid:      'Grid trading con niveles fijos',
    momentum:  'Momentum con detección de fuerza',
    mean:      'Mean reversion (reversión a la media)',
    breakout:  'Breakout de rango',
    dca:       'Dollar-cost averaging (DCA)',
    trend:     'Trend following en alta temporalidad',
    reversal:  'Reversión tras agotamiento',
    hedge:     'Hedging direccional',
  },
  en: {
    scalping:  'Fast scalping (M1-M5 timeframe)',
    swing:     'Swing trading (H4-D1 timeframe)',
    grid:      'Grid trading with fixed levels',
    momentum:  'Momentum with strength detection',
    mean:      'Mean reversion',
    breakout:  'Range breakout',
    dca:       'Dollar-cost averaging (DCA)',
    trend:     'Trend following on higher timeframes',
    reversal:  'Reversal after exhaustion',
    hedge:     'Directional hedging',
  },
};

// Helper para resolver la descripción de la estrategia o devolverla cruda.
export function strategyDesc(strategy: string, lang: Lang): string {
  return STRATEGY_DESC[lang][strategy] || strategy;
}

// Normaliza el lang
export function normLang(raw?: string | null): Lang {
  return raw === 'en' ? 'en' : 'es';
}
